### ISSUE TITLE
HTTP 500

### ISSUE THREAD

**Issue by drewtoma** [damcclean/simple-commerce#629]
### Bug Description

After upgrading to the new simple commerce when submitting an order I'm receiving a HTTP 500. The order is recorded as paid, and order emails sent.

### Steps to reproduce

```
[2022-05-12 15:34:18] local.ERROR: Order [e7cd956f-ec37-4bbc-888e-087b16e76be2] could not be found. {"userId":"b0a6033d-896f-41ba-a3e1-921b60fe7a1b","exception":"[object] (DoubleThreeDigital\\SimpleCommerce\\Exceptions\\OrderNotFound(code: 0): Order [e7cd956f-ec37-4bbc-888e-087b16e76be2] could not be found. at /Users/drewtoma/Sites/projectname/vendor/doublethreedigital/simple-commerce/src/Orders/EntryOrderRepository.php:38)
[stacktrace]
#0 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): DoubleThreeDigital\\SimpleCommerce\\Orders\\EntryOrderRepository->find('e7cd956f-ec37-4...')
#1 /Users/drewtoma/Sites/projectname/vendor/doublethreedigital/simple-commerce/src/Customers/Customer.php(73): Illuminate\\Support\\Facades\\Facade::__callStatic('find', Array)
#2 [internal function]: DoubleThreeDigital\\SimpleCommerce\\Customers\\Customer->DoubleThreeDigital\\SimpleCommerce\\Customers\\{closure}('e7cd956f-ec37-4...', 0)
#3 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(725): array_map(Object(Closure), Array, Array)
#4 /Users/drewtoma/Sites/projectname/vendor/doublethreedigital/simple-commerce/src/Customers/Customer.php(74): Illuminate\\Support\\Collection->map(Object(Closure))
#5 /Users/drewtoma/Sites/projectname/vendor/doublethreedigital/simple-commerce/src/Http/Controllers/CheckoutController.php(260): DoubleThreeDigital\\SimpleCommerce\\Customers\\Customer->orders()
#6 /Users/drewtoma/Sites/projectname/vendor/doublethreedigital/simple-commerce/src/Http/Controllers/CheckoutController.php(47): DoubleThreeDigital\\SimpleCommerce\\Http\\Controllers\\CheckoutController->postCheckout()
#7 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): DoubleThreeDigital\\SimpleCommerce\\Http\\Controllers\\CheckoutController->__invoke(Object(DoubleThreeDigital\\SimpleCommerce\\Http\\Requests\\Checkout\\StoreRequest))
#8 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('__invoke', Array)
#9 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(DoubleThreeDigital\\SimpleCommerce\\Http\\Controllers\\CheckoutController), '__invoke')
#10 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#11 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#12 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 /Users/drewtoma/Sites/projectname/vendor/doublethreedigital/simple-commerce/src/Http/Middleware/EnsureFormParametersArriveIntact.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): DoubleThreeDigital\\SimpleCommerce\\Http\\Middleware\\EnsureFormParametersArriveIntact->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#23 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#30 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#31 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#32 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#33 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#34 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/drewtoma/Sites/projectname/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /Users/drewtoma/Sites/projectname/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /Users/drewtoma/Sites/projectname/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Users/drewtoma/Sites/projectname/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /Users/drewtoma/Sites/projectname/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /Users/drewtoma/Sites/projectname/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#61 /Users/drewtoma/Sites/projectname/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#62 /Users/drewtoma/Sites/projectname/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#63 /Users/drewtoma/.composer/vendor/laravel/valet/server.php(214): require('/Users/drewtoma...')
#64 {main}
"}
```

### Environment

Statamic 3.3.11 Pro
Laravel 9.12.2
PHP 8.1.4
aryehraber/statamic-uuid 2.1.0
doublethreedigital/simple-commerce 3.0.1
edalzell/forma 1.1
kind-work/two-fa 1.5.1
rias/statamic-address-field 1.0.2
rias/statamic-redirect 2.2.0
silentz/akismet 3.1.1
silentz/mailchimp 2.9
statamic/seo-pro 3.1.0

> **Edit:** Parts of the original issue have been redacted after posting.

**Comment by duncanmcclean** [comment]
What does your checkout form look like?

**Comment by drewtoma** [comment]
Edit: Removed this code from the issue after the fact. The issue didn't end up having anything to do with the checkout form code anyways.
